language: node_js

node_js:
  - '8'

install:
  - node --version
  - npm --version
  - npm install
  - npm run build

os:
  - osx
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

script:
  - cd example && npm install && npm run programmatic

cache:
  directories:
    - node_modules
