language: node_js

node_js:
  - 8
  - 10
  - 12

os:
  - osx
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

script:
  - npm test
  - cd example && npm install && npm run programmatic
